### ISSUE TITLE
Your app is broken

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/shsd_ynh#2]
Hello

Your app is failing on our CI
https://ci-apps.yunohost.org/ci/job/558

Please try to fix this app before Sunday 21th, otherwise it will be set at notworking.
If you need help, don't hesitate to ask on our chat rooms,
- IRC: #yunohost-apps on irc.freenode.net
- Matrix: #freenode_#yunohost-apps:matrix.org
- XMPP: apps@conference.yunohost.org

**Comment by flesueur** [comment]
Hello,

I'll look into that (and other improvements) in the following weeks.. I hope :)

**Comment by flesueur** [comment]
Hi @maniackcrudelis ,

It seems to work better, I commented the rewrite line in nginx.conf
`location YNH_EXAMPLE_PATH/ {
 #    rewrite                ^YNH_EXAMPLE_PATH$ YNH_EXAMPLE_PATH/ permanent;
     proxy_pass             http://YNH_EXEMPLE_DOMAIN:YNH_EXAMPLE_PORT/;
     proxy_set_header       Host $host;
     proxy_buffering off;
}`

If the problem comes from here, the documentation may be out of date (https://yunohost.org/#/packaging_apps_nginx_conf/preview).

Even if the CI still emits some warnings (I need to work on them), can SHSD be readded to the list of installable applications ?

**Comment by maniackcrudelis** [comment]
Actually I'm quite sure the doc is out of date...

Have a look to the [example nginx conf](https://github.com/YunoHost/example_ynh/blob/master/conf/nginx.conf). The redirection has to be before the location block. In order to fix a potential alias traversal security issue.

**Comment by flesueur** [comment]
ok ;)

I rebased my nginx.conf on the one from the example app. Let me know if SHSD can be set as working again and if we can close this issue

**Comment by maniackcrudelis** [comment]
Your app can be set as working as soon as it's not level 0.
It's currently level 3, so you can.
